[phases.setup]
nixPkgs = ["ffmpeg"]

[phases.build]
cmds = ["mkdir -p /usr/local/bin && curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp && chmod +x /usr/local/bin/yt-dlp"]
